import { coffeeDirectoryVersion, coffeeProductDirectory } from "./coffeeProducts";

/** Discovery entries grant no vendor-content rights; the PMC entry has per-document licence records. */
export const knowledgeSources = [
	...coffeeProductDirectory.map((entry) => ({ id: `product-${entry.id}`, publisher: entry.manufacturer, url: entry.sourceUrl, type: "product_directory", scope: `${entry.product}; coffee forms: ${entry.forms.join(", ")}`, version: `${entry.sourceVersion ?? "源文版本未知"}; 自编目录 ${coffeeDirectoryVersion}`, terms: entry.termsUrl, limitation: `${entry.note} 仅自编目录入库；供应商全文许可待核实，参数未确认。`, robots: "人工核对入口；未批量采集供应商原文" })),
	{ id: "pmc-coffee-open", publisher: "Research authors / MDPI; PMC distributes", url: "https://pmc.ncbi.nlm.nih.gov/tools/pmcaws/", type: "research_report", scope: "7 篇咖啡包装、相关膜材料及储存研究，6 个文档家族；不是供应商 TDS", version: "coffee-open-v1 + coffee-open-v2 / PMC article .1 snapshots", terms: "https://creativecommons.org/licenses/by/4.0/", limitation: "按篇 CC BY 4.0 核验，研究样品不证明订单适用或认证。新增湿度论文测试取出原包装的速溶咖啡。1 篇 CC BY-NC-ND 已排除。", robots: "开放数据 API 明确允许自动获取；S3 robots.txt 404，不将其当作授权" },
	{ id: "mondi-paper", publisher: "Mondi", url: "https://www.mondigroup.com/products-and-solutions/flexible-packaging/paper-laminates/", type: "product_information", scope: "纸基复合软包装；不等于咖啡袋型号 TDS", version: "网页未标版本", terms: "https://www.mondigroup.com/legal-notice/", limitation: "版权保留；网页提供阻隔选项，不能推出具体厚度或 OTR。", robots: "已检查 https://www.mondigroup.com/robots.txt；授权另审" },
	{ id: "huhtamaki-coffee", publisher: "Huhtamaki", url: "https://www.huhtamaki.com/en/flexible-packaging/market-segments/beverages/coffee/ground-coffee/", type: "product_information", scope: "咖啡软包装；PE、PET/PE、PO 与纸基产品家族", version: "网页未标版本", terms: "https://www.huhtamaki.com/", limitation: "家族介绍不是逐型号测试报告；全文索引授权待确认。", robots: "未核实；禁止自动采集" },
	{ id: "amcor-coffee", publisher: "Amcor", url: "https://www.amcor.com/products/beverages/coffee/emea", type: "product_information", scope: "EMEA 咖啡包装、AmPrima 产品家族", version: "网页未标版本", terms: "https://www.amcor.com/", limitation: "宣传与认证、订单适用性分开；需索取型号数据和许可。", robots: "未核实；禁止自动采集" },
	{ id: "constantia-coffee", publisher: "Constantia Flexibles", url: "https://consumer.cflex.com/products/coffee-packaging/", type: "product_information", scope: "咖啡复合材料与袋型", version: "网页未标版本", terms: "https://consumer.cflex.com/", limitation: "下载入口已发现；批量获取与嵌入许可待核实。", robots: "未核实；禁止自动采集" },
	{ id: "avery-78838", publisher: "Avery Dennison", url: "https://label.averydennison.asia/content/dam/averydennison/lpm/na/en/product%20families/Data%20Sheets/Flexible%20Packaging/78838-PDS-en.pdf", type: "technical_datasheet", scope: "78838 软包装产品，3 页 PDF", version: "须人工核对原文修订标记", terms: "https://label.averydennison.asia/", limitation: "真实型号 TDS 入口；未获得全文持久化和公开再分发许可。", robots: "未核实；禁止自动采集" },
	{ id: "fefco", publisher: "FEFCO", url: "https://www.fefco.org/technical-information/fefco-code", type: "classification", scope: "瓦楞箱结构；后续扩展，不进入咖啡袋参数库", version: "12th edition", terms: "https://www.fefco.org/terms-of-use", limitation: "允许条件下阅读/研究，不代表可公开再分发或制作衍生数据库。", robots: "未核实；禁止自动采集" },
	{ id: "gs1-ppm", publisher: "GS1", url: "https://ref.gs1.org/standards/ppm/", type: "normative_document", scope: "产品与包装层级测量字段定义", version: "3.3 / Aug 2026 / 78 页", terms: "https://www.gs1.org/standards/ip", limitation: "标准实施许可不自动等于全文索引/再分发许可；PDF 正式版为准。", robots: "未核实；禁止自动采集" },
	{ id: "fsc-search", publisher: "FSC", url: "https://search.fsc.org/en/", type: "certificate_record", scope: "机构证书、许可及范围查询", version: "动态查询，保存时间戳才有版本意义", terms: "https://search.fsc.org/en/", limitation: "人工查询入口；未确认批量 API 权限。机构证书不证明某订单或产品认证。", robots: "未核实；禁止自动采集" },
	{ id: "eu-ppwr", publisher: "European Commission", url: "https://environment.ec.europa.eu/topics/waste-and-recycling/packaging-waste/packaging-packaging-waste-regulation_en", type: "regulatory_discovery", scope: "欧盟包装法规发现入口", version: "专题网页；正式法律文本另行核对", terms: "https://commission.europa.eu/legal-notice_en", limitation: "复用政策须逐项核对第三方例外；具体要求须追溯 EUR-Lex、适用日期和地区。", robots: "未核实；禁止自动采集" },
	{ id: "eurlex-2025-40", publisher: "European Union", url: "https://eur-lex.europa.eu/eli/reg/2025/40/oj/eng", type: "normative_document", scope: "Regulation (EU) 2025/40 正式入口", version: "OJ 原始版本入口，修订与合并版本须另查", terms: "https://eur-lex.europa.eu/content/legal-notice/legal-notice.html", limitation: "本次入口返回内容有限，未完成法律条文核验，不给合规结论。", robots: "未核实；禁止自动采集" },
	{ id: "cqc-food-contact", publisher: "中国质量认证中心", url: "https://www.cqc.com.cn/www/col68/596454.html", type: "certification_notice", scope: "食品接触材料相关认证标准换版通知，中文", version: "页面通知版本；国家标准全文另查", terms: "https://www.cqc.com.cn/", limitation: "认证机构官方通知不能替代国家标准，也不能证明订单符合要求。", robots: "未核实；禁止自动采集" },
].map((source) => ({
	...source, officialDomain: new URL(source.url).hostname, checkedAt: "2026-09-17T00:00:00.000Z",
	access: "manual_link", permission: "metadata_only", allowedUse: "保存自编的来源登记元数据和链接", redistribution: "不分发原文",
	updateFrequency: "发布者未承诺；拟每月人工检查，法规/证书在使用前重查", owner: "Packx 数据负责人（真实企业接入时指定）",
	trustBasis: "官方发布入口；仍需核对具体文档、版本和范围", ingestionStatus: "permission_review_required",
	...(source.id.startsWith("product-") ? { checkedAt: "2026-09-18T00:00:00.000Z", ingestionStatus: "metadata_import_available", updateFrequency: "自编目录 90 天复核；原始供应商有效期未知", trustBasis: "官方产品入口人工定位；仅保存自编发现元数据和链接" } : {}),
	...(source.id === "pmc-coffee-open" ? { checkedAt: "2026-09-18T02:30:09.123Z", access: "official_open_dataset_https", permission: "CC BY 4.0; per-document checked", allowedUse: "保留署名、许可、来源及修改说明后保存和索引", redistribution: "CC BY 4.0，保留署名和许可", ingestionStatus: "7_real_fulltexts_available", trustBasis: "出版论文原文与许可证、发布者 MD5、本地 SHA-256", updateFrequency: "使用前核对 PMC 修订/撤回；本次固定快照" } : {}),
}));

export const knowledgeCoverage = [
	{ category: "咖啡豆/咖啡粉/速溶咖啡产品目录", material: "PE / PP / 纸基等检索标签，层序未确认", process: "复合/制袋/封口线索，型号工艺待核实", application: "按咖啡形态过滤，避免跨用途推荐", region: "供应商入口范围；订单地区待确认", publishers: ["Constantia Flexibles", "Huhtamaki", "Amcor"], status: "6_product_series_metadata_only", missing: "获准的型号 TDS、厚度/公差、阻隔测试条件、封口/阀验证、订单适用性；不代表主流市场覆盖" },
	{ category: "咖啡纸包/胶囊/生豆包装及研究薄膜", material: "PET/Al/PE、PP、PET/MPET/PE、LDPE、PLA", process: "复合、制膜、储存与阻隔测试", application: "研究样品；咖啡渣/银皮膜是相邻应用", region: "实验室条件，订单地区未知", publishers: ["MDPI / research authors"], status: "5_licensed_research_fulltexts", missing: "供应商在售型号、订单适用性、中文资料、专业人工标注；不能据此声明市场覆盖" },
	{ category: "咖啡袋及开封速溶咖啡储存", material: "EVOH 真空袋、纸/铝/PE 复合、实验铝容器", process: "抽真空、阀/拉链包装、加速储存及湿度测试", application: "研究样品；湿度论文不测试密封袋", region: "研究地点及实验条件，不证明订单适用地区", publishers: ["Fernandez-Rosillo et al. / MDPI", "Instant coffee humidity study authors / MDPI"], status: "2_additional_licensed_fulltexts", missing: "在售型号 TDS、OTR/WVTR 明确测试条件、人工工业审核；源文异常单位保留待核对" },
	{ category: "咖啡豆/咖啡粉包装袋", material: "PE / PET-PE / PO / 纸基复合", process: "复合/制袋/封口/阀", application: "咖啡", region: "供应商页面范围，订单待核对", publishers: ["Mondi", "Huhtamaki", "Amcor", "Constantia Flexibles", "Avery Dennison"], status: "discovery_only", missing: "逐型号结构、厚度、OTR/WVTR 测试条件、许可、适用日期" },
	{ category: "咖啡袋", material: "食品接触塑料", process: "测试/认证", application: "食品接触", region: "CN", publishers: ["中国质量认证中心"], status: "discovery_only", missing: "正式标准版本与授权、具体型号测试报告" },
	{ category: "包装层级", material: "不指定", process: "测量", application: "产品数据交换", region: "global", publishers: ["GS1"], status: "definition_candidate", missing: "许可复核；不用于自动推算生产尺寸" },
	{ category: "瓦楞箱", material: "瓦楞纸板", process: "结构分类", application: "运输包装", region: "global", publishers: ["FEFCO"], status: "deferred", missing: "首个咖啡袋闭环通过后再扩展" },
	{ category: "纸基包装", material: "森林来源材料", process: "证书查询", application: "供应链核查", region: "证书范围", publishers: ["FSC"], status: "discovery_only", missing: "订单关联、批量授权、有效期与范围核验" },
	{ category: "包装", material: "跨材料", process: "法规核查", application: "上市地区规则", region: "EU", publishers: ["European Commission", "European Union"], status: "discovery_only", missing: "条款版本、生效/适用日期、专业审查" },
];
